var ActionTypes = {
  // MARK_NOTIFICATION_AS_READ: null,
  // MARK_ALL_NOTIFICATION_AS_READ: null,
  // SEEK_TO_TIME: null,
  // CREATE_BOOKMARK: null,
  // DELETE_BOOKMARK: null,
  REPLY_SUBMIT: 'REPLY_SUBMIT',
  CREATE_COMMENT: 'CREATE_COMMENT',
  REQUEST_COMMENTS: 'REQUEST_COMMENTS',

  EDIT_BOOKMARK_BEGIN: 'EDIT_BOOKMARK_BEGIN',
  EDIT_BOOKMARK_CANCEL: 'EDIT_BOOKMARK_CANCEL',
  EDIT_BOOKMARK_SUBMIT: 'EDIT_BOOKMARK_SUBMIT',
  CREATE_BOOKMARK: 'CREATE_BOOKMARK',
  REQUEST_BOOKMARKS: 'REQUEST_BOOKMARKS'
}

module.exports = ActionTypes;
