var ActionTypes = {

  CREATE_COURSE: 'CREATE_COURSE',
  CREATE_LECTURE: 'CREATE_LECTURE',
  CREATE_COMMENT: 'CREATE_COMMENT',
  CREATE_REPLY: 'CREATE_REPLY',
  CREATE_BOOKMARK: 'CREATE_BOOKMARK',

  REQUEST_COURSES: 'REQUEST_COURSES',
  REQUEST_LECTURES: 'REQUEST_LECTURES',
  REQUEST_COMMENTS: 'REQUEST_COMMENTS',
  REQUEST_BOOKMARKS: 'REQUEST_BOOKMARKS',

  UPDATE_BOOKMARK: 'UPDATE_BOOKMARK',

  DELETE_BOOKMARK: 'DELETE_BOOKMARK'
}

module.exports = ActionTypes;
