var ActionTypes = {
  REPLY_BEGIN: 'REPLY_BEGIN',
  REPLY_CANCEL: 'REPLY_CANCEL',
  REPLY_SUBMIT: 'REPLY_SUBMIT',
  // MARK_NOTIFICATION_AS_READ: null,
  // MARK_ALL_NOTIFICATION_AS_READ: null,
  // SEEK_TO_TIME: null,
  CREATE_COMMENT: 'CREATE_COMMENT',
  // CREATE_BOOKMARK: null,
  // DELETE_BOOKMARK: null,
  REQUEST_COMMENTS: 'REQUEST_COMMENTS'
}

module.exports = ActionTypes;
